= *Nemesis CMS Console - user guide*
:toc:

This guide shows you how to use the Nemesis CMS console. If this is your first time to work with the console, check our Overview article link:https://docs.nemesis.io/current-snapshot/nemesis-console-v2/index.html[here]). Once logged, you are ready to start the tutorial below:

== *Start the CMS console*
To open the CMS live edit, click `Live edit` in the navigation bar and choose the site you want to edit. You see it opened in a new window.

== *The navigation bar*

By default, the *Navigation bar* of the CMS console is in the left side of your screen.

IMPORTANT: Currently, in order to see the list of the available widgets, you need to have the stage catalogs activated. Please, check the value of the `enableCatalogVersions` property in the `application.properties` file of your application, and if `FALSE`, set it to `TRUE`.

The *Navigation bar* shows
    * a paginated list of the stage widgets;
    * a `Live edit` button;
    * a `Show all` button;
    * a search bar;

The *paginated list of widgets* shows all widgets, available among all stage catalogs. When you hover on a widget, you will see information for:
* 1st) its code;
* 2nd) its name;
* 3rd) its catalog;

When you switch on the *Live edit*, you see all of the currently *visible* slots and widgets inside.

NOTE: Visually, each *slot* is outlined in *red*, whereas each *widget* is outlined in *blue*.


When you switch on the *Show all* ONLY, you activate the *empty slots* and the *non-initialized slots*. That is why, visually, you will see that the site's content is pushed aside.

To get a clear idea what is going on, switch on the *Live edit* as well. The empty slots are in red (as usual), without the blue line inside (without a widget, in other words). The non-initialized slots, if any, are in green. More on what a non-initialized slot is read below.

In the *search bar* you may search against the database of all widgets in the stage catalogs. The search criteria is the *widget code*. If the code you enter is *contained* in any of the widget codes available, the match is displayed.

== *How to reorder your widgets*

All of the widgets available are enumerated in the navigation bar and can be searched by their code. When you find the widget you want, just drag and drop it in a slot - either an empty, of a filled-in one. When the widget is placed in the slot, the page is reloaded and you can see the changes you have just made.

IMPORTANT: New widgets and slots *cannot* be created in the CSV console. You can only edit the way they are located on the site. In order to create a new widget or a new slot, you need the *Backend console*.

== *How to modify the content of a widget*

Each of the widgets, enumerated in the navigation bar, has s 3-dot-button on top. When you click it, the Backend console gets opened (or asks you to log in and opens after that) and you are navigated to the respective widget. From the Backend console now, you can edit your widget. If you have any doubts on how to work with the Backend Console, check link:user-guide.html[this] guide.

When you click `Close`, you are returned on the current page, without any changes in the visualization.

When you click `Reload changes`, the page gets reloaded and you see the changes in the visualization.

NOTE: Do not forget to click `SAVE` if you want to store the changes in the database.

== *How to remove a widget from a slot*

When the `Live edit` is ON, you see the slots outlined in red. Click on the 3-dot red button to open the respective slot in the backend console. From there, navigate to the `Widgets` section and `Remove` the widgets you'd want to. Do not forget to `SAVE` your changes.

If you want to see the change of the visualization, click `Reload changes`.

== *How to work with non-initialized slots*

There is a case in which you decide to delete a slot, but later want to use it again and to insert a widget inside.

First, you go to the respective slot, click on the 3-dot red button and click `Delete` to delete the slot.

Then reload the page and switch on the `Live edit` and `Show all`.

What you notice now is that there is a green rectangle outlined on the place where the deleted slot was. This green rectangle shows that there was a slot there before and this slot may be used again.

Drag and drop a widget from the navigation bar.

A pop-up appears, asking you to create a slot first. You need to choose if this slot is to apply to the whole template (in other words, on every page on this place) or to the respective page only. Choose the option you want.

Then enter the slot's code (an obligatory requisite for each and every slot).

Click `Create`. You have just created a new slot with the entered code and your widget is inserted inside.




